### ISSUE TITLE
Support embedding a group calendar

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/bp-event-organiser#46]
Users should be able to embed the group calendar on other sites.

**Update:**

Appending `?embedded=true` will remove the header and footer on group event pages:
- `example.com/groups/GROUP/events/?embedded=true`
- `example.com/groups/GROUP/events/upcoming/?embedded=true`

This will allow for embedding with an IFRAME.

**Todos:**
- [x] Override wrapper group template to remove the header and footer (commits e21ae70 / 438960c)
- [x] Create a specialized widget plugin that will embed an IFRAME of the group calendar on sub-sites (commit 4f40d69)
- [x] Support shortcodes and Shortcake plugin
